predict_price/urls.py
from django.urls import path
from . import views 

app_name = 'predict_price'

urlpatterns = [
    path('', views.first_view, name='first_view'),  
    path('inprocess/', views.inprocess, name='inprocess'),
    # path('prediction/', views.prediction, name='prediction'), # original
    path('prediction/<str:apt_name>/<str:price>/<str:apt_average>/<str:dong_average>', views.prediction, name='prediction'), # added
]

predict_price/models.py
from django.db import models

# Create your models here.

class Apartment(models.Model):
    gu = models.CharField(max_length=200)
    dong = models.CharField(max_length=200)
    sell = models.IntegerField(default=0)
    size = models.FloatField(default=0.0)
    floor = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    cstr_date = models.IntegerField(default=0)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Dong(models.Model):
    dong = models.CharField(max_length=200)

    def __str__(self):
        return self.dong
    
class Apt(models.Model):
    gu = models.CharField(max_length=200)
    dong = models.CharField(max_length=200)
    sell = models.IntegerField(default=0)
    size = models.FloatField(default=0.0)
    floor = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    cstr_year = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    built_year = models.IntegerField(default=0)
    brand_score = models.IntegerField(default=0)
    trade_index = models.FloatField(default=0.0)

    def __str__(self):
        return self.name

predict_price/views.py
from django.shortcuts import render
from .models import Apartment, Dong, Apt
import pandas as pd
from django.db.models import Count
from .predict_ml import prediction_ml, selected_apt_avg, selected_dong_avg


def first_view(request):

    # print("*******************")
    # print(name_list)
    # print("*******************")
    # print(dong_name_group)

    apt_list = Apt.objects.order_by('gu').values('gu', 'dong').distinct().order_by('dong')   
    gu_dong_group = {} # {'강남구': ['대치동', '압구정동', '도곡동',...], '강동구': ['상일동', '암사동', '길동', ...] ... }
    for gu_dong_each in apt_list :
        if gu_dong_each['gu'] not in gu_dong_group.keys() :
            gu_dong_group[gu_dong_each['gu']] = [gu_dong_each['dong']] # [] 감싸서 강제로 list로 전환 하여 append 할수 있게함
        else:
            gu_dong_group[gu_dong_each['gu']].append(gu_dong_each['dong'])

    name_list = Apt.objects.order_by('dong').values('dong', 'name').distinct().order_by('name')
    dong_name_group = {}
    for dong_name_each in name_list:
        if dong_name_each['dong'] not in dong_name_group.keys():
            dong_name_group[dong_name_each['dong']] = [dong_name_each['name']]
        else:
            dong_name_group[dong_name_each['dong']].append(dong_name_each['name'])

    size_list = Apt.objects.order_by('name').values('name', 'size').distinct().order_by('size')
    name_size_group = {}
    for name_size_each in size_list:
        if name_size_each['name'] not in name_size_group.keys():
            name_size_group[name_size_each['name']] = [name_size_each['size']]
        else:
            name_size_group[name_size_each['name']].append(name_size_each['size'])

    floor_list = Apt.objects.order_by('name').values('name', 'floor').distinct().order_by('floor')
    name_floor_group = {}
    for name_floor_each in floor_list:
        if name_floor_each['name'] not in name_floor_group.keys():
            name_floor_group[name_floor_each['name']] = [name_floor_each['floor']]
        else:
            name_floor_group[name_floor_each['name']].append(name_floor_each['floor'])

    cstr_year_list = Apt.objects.order_by('name').values('name', 'cstr_year').distinct().order_by('cstr_year')
    name_cstr_year_group = {}
    for name_cstr_year_each in cstr_year_list:
        if name_cstr_year_each['name'] not in name_cstr_year_group.keys():
            name_cstr_year_group[name_cstr_year_each['name']] = [name_cstr_year_each['cstr_year']]
        else:
            name_cstr_year_group[name_cstr_year_each['name']].append(name_cstr_year_each['cstr_year'])

    built_year_list = Apt.objects.order_by('name').values('name', 'built_year').distinct().order_by('built_year')
    name_built_year_group = {}
    for name_built_year_each in built_year_list:
        if name_built_year_each['name'] not in name_built_year_group.keys():
            name_built_year_group[name_built_year_each['name']] = [name_built_year_each['built_year']]
        else:
            name_built_year_group[name_built_year_each['name']].append(name_built_year_each['built_year'])

    brand_score_list = Apt.objects.order_by('name').values('name', 'brand_score').distinct().order_by('brand_score')
    name_brand_score_group = {}
    for name_brand_score_each in brand_score_list:
        if name_brand_score_each['name'] not in name_brand_score_group.keys():
            name_brand_score_group[name_brand_score_each['name']] = [name_brand_score_each['brand_score']]
        else:
            name_brand_score_group[name_brand_score_each['name']].append(name_brand_score_each['brand_score'])

    # print("*******************")
    # print(floor_list)
    # print("*******************")
    # print(name_floor_group)

    context = {'gu_dong_group':gu_dong_group, 'dong_name_group':dong_name_group, 'name_size_group':name_size_group,
               'name_floor_group':name_floor_group, 'name_cstr_year_group':name_cstr_year_group, 'name_built_year_group':name_built_year_group,
               'name_brand_score_group':name_brand_score_group,
               }
    
    return render(request, 'predict_price/first_view.html', context)


def prediction(request, apt_name, price, apt_average, dong_average):
    
    # 최선도 님과 함께
    # - 아파트가 속한 동 내 아파트 평균가 계산
    # - 해당 아파트의 평균가 계산
    # -> 이 2가지 계산이 끝난 후 아래 context 에 포함시켜 result.html 에서 보여주셔요!
    
    context = {'apt_name':apt_name, 'price':price, 'apt_average':apt_average, 'dong_average':dong_average}
    
    return render(request, 'predict_price/result.html', context)


def inprocess(request):
    value_gu = request.POST['select_input_gu']
    value_dong = request.POST['select_input_dong']
    value_apt = request.POST['select_input_apt']
    value_size = request.POST['select_input_size']
    value_floor = request.POST['select_input_floor']
    value_cstr_year = request.POST['select_input_cstr_year']
    value_built_year = request.POST['select_input_built_year']
    value_brand_score = request.POST['select_input_brand_score']
    value_trade_index = request.POST['select_input_trade_index']
    value_sell = request.POST['select_input_sell']
    
    print(type(value_gu), value_gu)
    print(type(value_dong), value_dong)
    print(type(value_apt), value_apt)
    print(type(value_size), value_size)
    print(type(value_floor), value_floor)
    print(type(value_cstr_year), value_cstr_year)
    print(type(value_built_year), value_built_year)
    print(type(value_brand_score), value_brand_score)
    print(type(value_trade_index), value_trade_index)
    print(type(value_sell), value_sell)
  
    predict_result = prediction_ml(value_gu, value_dong, value_apt, value_size, value_floor, value_cstr_year, value_built_year, value_brand_score,
                                value_trade_index, value_sell)

    apt_avg = selected_apt_avg(value_gu, value_dong, value_apt)

    dong_avg = selected_dong_avg(value_gu, value_dong)    
    
    context = {'value_apt':value_apt, 'predict_result':predict_result, 'apt_avg':apt_avg, 'dong_avg':dong_avg}

    return render(request, 'predict_price/inprocess.html', context) 

    # test = "800000"
    
    # return render(request, 'predict_price/inprocess.html', {'test':test})

templates/predict_price/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>아파트값 예측</title>

<!--  <link href="//fonts.googleapis.com/css?family=Do+Hyeon|Noto+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'predict_price/style.css' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link href="//fonts.googleapis.com/css?family=Do+Hyeon|Noto+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'predict_price/style.css' %}"/>

</head>
<body>
    <div class="top"></div>
    {% block content %}
    {% endblock %}
<footer class="footer">
    <div class="container">
        <p class="text-muted">Team "내일의집" Reserved</p>
    </div>
</footer>
</body>
</html>

templates/predict_price/inprocess.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>아파트값 예측</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link href="//fonts.googleapis.com/css?family=Do+Hyeon|Noto+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'predict_price/style.css' %}"/>

  <!-- <META http-equiv="refresh" content="3; { % url 'predict_price:prediction' % }"> -->

  <!-- 방안 1. url에 정보를 담아서 view에서 get 방식으로 data 저장 후 전달하기 -->
  <!-- 방안 2. post 할 수 있도록 hidden으로 담아서 버튼 눌러서 전달하기 (이러면 자동으로 계산되는 것 처럼 보여주는 취지에 어긋남)-->
  <!-- 방안 3. Javascript를 사용해서 전달? -->

</head>
<body>
<div class="text-center" style="padding-top:10%; color:white;">
    <br>
    <br>
    <h1>Calculating...</h1>
    <br>
    <br>
</div>

<div class="text-center">
    <div class="spinner-border text-success" role="status" style="width: 240px; height: 240px;">
        <span class="visually-hidden"></span>
    </div>
</div>

  <script language = "javascript">

    var result = '{{ predict_result }}';
    var apt = '{{ value_apt }}'; // added 
    var apt_average = '{{ apt_avg }}'
    var dong_average = '{{ dong_avg }}'

    setTimeout(function(){
      location.href="/prediction/" + apt + "/" + result + "/" + apt_average + "/" + dong_average; // added
    }, 5000);
  </script>

</body>

</html>

templates/predict_price/result.html
{% extends 'predict_price/base.html' %}
{% block content %}


{% comment %} <script language = "javascript">
    temp = location.href.split("?");
    data=temp[1];

    document.write("<div class='last_page_middle'><h1>"+"예측가격은 "+data+"억 원입니다."+"</h1></div>");   //페이지에 전달받은 값 띄워서 확인하기 
    console.log("TAGTAG : " + data);    //콘솔에 전달받은 값 띄워서 확인하기
</script> {% endcomment %}


{% comment %} <div class="last_page_top">
    <h1> A program to predict housing prices in Seoul </h1>
</div> {% endcomment %}


<div id='building_thumbnail'>
    <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill="white" class="bi bi-building" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
    <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
    </svg>
</div>

<div class='last_page_middle'>
    <h1>선택하신 {{ apt_name }} 의</h1>
    <h1 class='under'>예측가격은 {{ price }} 억 원입니다.</h1>
    <br>
    <h2>선택된 아파트 단지의 평균가격은 {{ apt_average }} 억 원입니다. </h2>
    <h2>선택된 동의 아파트 평균가격은  {{ dong_average }} 억 원입니다. </h2>
</div>


<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: '연도별 서울 아파트 가격(단위: 억 원)'
    },
    xAxis: {
        categories: ['2017년', '2018년', '2019년', '2020년', '2021년']
    },
    series: [{
        name: '초소형(40㎡ 이하)',
        data: [3.5, 3.6, 4.1, 4.4, 5.0]
    }, {
        name: '소형(40㎡초과 60㎡이하)',
        data: [4.6, 4.9, 6.0, 6.9, 8.4]
    }, {
        name: '중소형(60㎡초과 85㎡이하)',
        data: [6.3, 6.6, 8.3, 9.1, 11.2]
    }, {
        name: '중대형(85㎡초과 135㎡이하)',
        data: [10.2, 10.7, 13.4, 14.3, 18.3]
    }
    ]
});
</script>


<div class="last_page_bottom">
    <p><a href="{% url 'predict_price:first_view' %}">Return to home</a></p>
</div>


{% endblock %}